# Generated by Django 4.0.4 on 2022-05-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='image_category',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Vehicles', 'Vehicles'), ('People', 'People'), ('Travel', 'Travel'), ('Food', 'Food'), ('People', 'People'), ('Sky', 'Sky'), ('Animals', 'Animals')], max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
