# Generated by Django 4.0.4 on 2022-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('US', 'US'), ('Europe', 'Europe'), ('Australia', 'Australia'), ('Antarctica', 'Antarctica'), ('SA', 'SA')], max_length=30),
        ),
    ]
